apu_setcontext not defined in header
Missing declaration void apu_setcontext(apu_t *src_apu)

Should fix build failure
```
/Users/Shared/jenkins/workspace/TVOS/tools/depends/target/binary-addons/appletvos13.2_arm64-target-release/build/audiodecoder.nosefart/lib/nosefart/src/machine/nsf.c:327:5: error: implicit declaration of function 'apu_setcontext' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     apu_setcontext(nsf->apu);
```